InkWorks/Controllers/ClientesController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using InkWorks.Filters;
using InkWorks.Models;
using InkWorks.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace InkWorks.Controllers
{
    [UtilizadorLogado]
    public class ClientesController : Controller
    {
        private readonly IClienteRepositorio _repositorio;
        private readonly IMensagemRepositorio _mensagem;
        private readonly ITrabalhoRepositorio _trabalho;
        private readonly INotyfService _notification;
        public ClientesController(IClienteRepositorio repositorio, INotyfService notification, IMensagemRepositorio mensagem, ITrabalhoRepositorio trabalho)
        {
            _repositorio = repositorio;
            _notification = notification;
            _mensagem = mensagem;
            _trabalho = trabalho;
        }
        public IActionResult Index()
        {
            //Pedir dados
            List<Cliente> clientes = _repositorio.ListarTodos();
            // Passa os dados para a view
            return View("Index", clientes);
        }
        public IActionResult Adicionar()
        {
            return View();
        }
        public IActionResult AdicionarPorMsg(int id)
        {
            Mensagem mensagem = _mensagem.ListarPorId(id);

            if (mensagem == null)
            {
                _notification.Error("Não encontrado!");
                return RedirectToAction("Index");
            }

            Cliente novoCliente = new Cliente
            {
                Nome = mensagem.Nome,
                Email = mensagem.Email,
                Morada = mensagem.Morada,
                AnoNascimento = mensagem.AnoNascimento,
                Telefone = mensagem.Telefone,
                MsgId = mensagem.MensagemId
            };


            return View("AdicionarPorMsg", novoCliente);
        }
        public IActionResult Detalhes(int id)
        {

            var cliente = _repositorio.ListarDetalhesPorId(id);
            if (cliente == null)
            {
                _notification.Error("Cliente não encontrado!");
                return RedirectToAction("Index");
            }
            return View(cliente);
        }

        public IActionResult Editar(int id)
        {

            Cliente cliente = _repositorio.ListarPorId(id);

            if (cliente == null)
            {
                _notification.Error("Cliente não encontrado!");
                return RedirectToAction("Index");
            }

            return View(cliente);
        }
        public IActionResult Eliminar(int id)
        {

            Cliente cliente = _repositorio.ListarPorId(id);

            if (cliente == null)
            {
                _notification.Error("Cliente não encontrado!");
                return RedirectToAction("Index");
            }

            return View(cliente);
        }

        [HttpPost]
        public IActionResult Adicionar(Cliente cliente)
        {

            _repositorio.Adicionar(cliente);
            _notification.Success("Cliente adicionado");
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Editar(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _repositorio.Editar(cliente);
                _notification.Success("Cliente Editado!");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Eliminar(Cliente cliente)
        {
            if (cliente == null)
            {
                _notification.Error("Cliente não encontrado!");
                return RedirectToAction("Index");
            }
            _repositorio.Eliminar(cliente);
            _notification.Success("Cliente eliminado");


            return RedirectToAction("Index");

        }
        [HttpPost]
        public IActionResult AdicionarPorMsg(Cliente cliente)
        {
            int? msgIdNullable = cliente.MsgId;
            int msgId = msgIdNullable.HasValue ? msgIdNullable.Value : 0;


            var mensagem = _mensagem.ListarPorId(msgId);

            if (mensagem != null)
            {

                mensagem.Cliente = cliente;
                mensagem.ClienteId = cliente.ClienteId;

                mensagem.Nome = cliente.Nome;
                mensagem.Email = cliente.Email;
                mensagem.Morada = cliente.Morada;
                mensagem.AnoNascimento = cliente.AnoNascimento;
                mensagem.Telefone = cliente.Telefone;

                _repositorio.Adicionar(cliente);

                _notification.Success("Cliente adicionado com a mensagem associada");
                return RedirectToAction("Index");
            }

            //  situação em que não foi encontrada uma mensagem válida
            _notification.Error("A mensagem não pôde ser associada ao cliente.");
            return View("Adicionar", cliente);
        }






    }
}

InkWorks/Controllers/ImagensController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using InkWorks.Filters;
using InkWorks.Models;
using InkWorks.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace InkWorks.Controllers
{
    [UtilizadorLogado]
    public class ImagensController : Controller
    {
        private readonly IImagemRepositorio _repositorio;
        private readonly ITrabalhoRepositorio _trabalhos;
        private readonly INotyfService _notification;
        public ImagensController(IImagemRepositorio repositorio, INotyfService notification, ITrabalhoRepositorio trabalhos)
        {
            _repositorio = repositorio;
            _notification = notification;
            _trabalhos = trabalhos;
        }
        public IActionResult Index()
        {
            var imagens = _repositorio.ListarTodos();
            var trabalhos = _trabalhos.ListarTodos();

            var viewModel = new ImagemTrabalhoViewModel
            {
                Imagens = imagens,
                Trabalhos = trabalhos
            };

            return View(viewModel);
        }

        public IActionResult Editar(int id)
        {
            Imagem img = _repositorio.ListarPorId(id);
            var trabalhos = _trabalhos.ListarTodos();

            if (img == null)
            {
                _notification.Error("Imagem não encontrada!");
                return RedirectToAction("Index");
            }

            var viewModel = new ImagemTrabalhoViewModel
            {
                Imagens = new List<Imagem> { img },
                Trabalhos = trabalhos
            };

            return View(viewModel);
        }
        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            Imagem img = _repositorio.ListarPorId(id);
            if (img == null)
            {
                _notification.Error("Imagem não encontrada!");
                return RedirectToAction("Index");
            }
            return View(img);
        }




        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile imagem, string titulo, string descricao, bool galeria, int TrabalhoId)
        {
            if (imagem != null && imagem.Length > 0)
            {
                try
                {

                    var uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads");


                    if (!Directory.Exists(uploadsFolder))
                    {
                        Directory.CreateDirectory(uploadsFolder);
                    }


                    var nomeArquivo = Guid.NewGuid().ToString() + Path.GetExtension(imagem.FileName);

                    var caminhoCompleto = Path.Combine(uploadsFolder, nomeArquivo);

                    using (var stream = new FileStream(caminhoCompleto, FileMode.Create))
                    {
                        await imagem.CopyToAsync(stream);
                    }


                    Imagem imagemModel;


                    imagemModel = new Imagem
                    {
                        Url = "/uploads/" + nomeArquivo,
                        Titulo = titulo,
                        Descricao = descricao,
                        Portfolio = galeria,
                        TrabalhoId = TrabalhoId != 0 ? TrabalhoId : (int?)null
                    };


                    _repositorio.Adicionar(imagemModel);

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    _notification.Error("Não Conseguimos carregar a sua imagem :(");
                }
            }

            _notification.Error("Oops!! Algo deu errado! tente novamente!");
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Editar(ImagemTrabalhoViewModel viewModel)
        {

            Imagem imagemExistente = _repositorio.ListarPorId(viewModel.Imagens[0].ImagemId);
            if (imagemExistente != null)
            {
                imagemExistente.Titulo = viewModel.Imagens[0].Titulo;
                imagemExistente.Descricao = viewModel.Imagens[0].Descricao;
                imagemExistente.Portfolio = viewModel.Imagens[0].Portfolio;
                imagemExistente.TrabalhoId = viewModel.TrabalhoId != 0 ? viewModel.TrabalhoId : (int?)null;

                _repositorio.Editar(imagemExistente);
                _notification.Success("Dados da Imagem atualizados!");
                return RedirectToAction("Index");
            }
            else
            {

                _notification.Error("Imagem não encontrada.");
                return View(viewModel);
            }

        }


        public IActionResult ConfirmaEliminar(int id)
        {
            Imagem imagem = _repositorio.ListarPorId(id);

            if (imagem == null)
            {
                _notification.Error("Imagem não encontrada!");
                return RedirectToAction("Index");
            }

            
            _repositorio.Eliminar(imagem);

           
            if (!string.IsNullOrEmpty(imagem.Url))
            {
                var imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", imagem.Url.TrimStart('/'));
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
            }

            _notification.Success("Imagem eliminada");
            return RedirectToAction("Index");
        }


    }
}

InkWorks/Controllers/LoginController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using InkWorks.Helper;
using InkWorks.Models;
using InkWorks.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace InkWorks.Controllers
{
    public class LoginController : Controller
    {
        private readonly INotyfService _notification;
        private readonly IUtilizadorRepositorio _user;
        private readonly ISessao _sessao;
        public LoginController(INotyfService notification, IUtilizadorRepositorio user, ISessao sessao)
        {
            _notification = notification;
            _user = user;
            _sessao = sessao;
        }
        public IActionResult Index()
        {
            //se já estiver logado, redireciona para área restrita
            if (_sessao.BuscarSessaoUtilizador() != null) return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpPost]
        public IActionResult Entrar(LoginModel login)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Utilizador user = _user.ListartPorLogin(login.Email);

                    if (user != null)
                    {
                        if (user.PasswordValida(login.Password))
                        {
                            _sessao.CriarSessaoUtilizador(user);
                            _notification.Success("Autenticado com sucesso!");
                            return RedirectToAction("Index", "Home");
                        }
                        _notification.Error("Email e/ou  passord incorretas");
                        return RedirectToAction("Index", "Login");
                    }

                    _notification.Error("Email e/ou  passord incorretas");
                    return RedirectToAction("Index", "Login");



                }
                _notification.Error("Introduza as credenciais corretas");
                return View("Index");
            }
            catch (Exception)
            {

                _notification.Error("Não conseguimos realizar o Login, tente novamente!");
                return RedirectToAction("Index");
            }

        }

        public IActionResult Logout()
        {
            _sessao.RemoverSessaoUtilizador();
            _notification.Success("Foi desligado com sucesso!");
            return RedirectToAction("Index", "Login");
        }
    }
}

InkWorks/Controllers/SessoesController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using InkWorks.Filters;
using InkWorks.Migrations;
using InkWorks.Models;
using InkWorks.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace InkWorks.Controllers
{
    [UtilizadorLogado]
    public class SessoesController : Controller
    {
        private readonly ISessaoRepositorio _repositorio;
        private readonly ITrabalhoRepositorio _repositorioTrabalhos;
        private readonly IClienteRepositorio _repositorioClientes;
        private readonly INotyfService _notification;
        public SessoesController(ISessaoRepositorio repositorio, ITrabalhoRepositorio repositorioTrabalhos, INotyfService notification, IClienteRepositorio repositorioClientes)
        {
            _repositorio = repositorio;
            _repositorioTrabalhos = repositorioTrabalhos;
            _repositorioClientes = repositorioClientes;
            _notification = notification;
        }

        public IActionResult Index()
        {
            //Pedir dados
            List<Sessao> sessoes = _repositorio.ListarTodos();
            if(sessoes == null)
            {
                _notification.Error("Erro ao carregar sessões!");
                return RedirectToAction("Index");
            }
            return View("Index", sessoes);
        }
        public IActionResult Adicionar(int TrabalhoId)
        {
            var trabalho = _repositorioTrabalhos.ListarPorId(TrabalhoId);

            if (trabalho == null)
            {
                _notification.Error("Trabalho não encontrado!");
                return RedirectToAction("Index");
            }

            var sessao = new Sessao
            {
                TrabalhoId = TrabalhoId,
                Trabalho = trabalho
            };
            return View(sessao);
        }
        public IActionResult Detalhes(int id)
        {
            Sessao sessao = _repositorio.ListarPorId(id);
            if (sessao == null)
            {
                _notification.Error("Erro ao carregar detalhes!");
                return RedirectToAction("Index");
            }
            return View(sessao);

        }


        public IActionResult Editar(int id)
        {

            Sessao sessao = _repositorio.ListarPorId(id);
           

            if (sessao == null)
            {
                _notification.Error("Não foi possível editar esta sessão!");
                return RedirectToAction("Index");
            }

            return View(sessao);
        }
        public IActionResult Eliminar(int id)
        {

            Sessao sessao = _repositorio.ListarPorId(id);

            if (sessao == null)
            {
                _notification.Error("Não foi possível apagar esta sessão!");
                return RedirectToAction("Index");
            }


            return View(sessao);
        }

        [HttpPost]
        public IActionResult Adicionar(Sessao sessao)
        {
            if (sessao == null)
            {
                _notification.Error("Erro ao carregar sessão!");
                return RedirectToAction("Index");
            }

            sessao.Duracao = (int)(sessao.DataFinal - sessao.DataInicio).TotalHours;

            _repositorio.Adicionar(sessao);
            _repositorioTrabalhos.AtualizarTotalHorasParaTrabalho(sessao.TrabalhoId);
            _notification.Success("Sessão marcada!");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Editar(Sessao sessao)
        {
            if (sessao == null)
            {
                _notification.Error("Erro ao carregar sessão!");
                return RedirectToAction("Index");
            }
            sessao.Duracao = (int)(sessao.DataFinal - sessao.DataInicio).TotalHours;

            _repositorio.Editar(sessao);
            _repositorioTrabalhos.AtualizarTotalHorasParaTrabalho(sessao.TrabalhoId);
            _notification.Success("Sessão modificada!");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Eliminar(Sessao sessao)
        {
            if (sessao == null)
            {
                _notification.Error("Erro ao carregar sessão!");
                return RedirectToAction("Index");
            }
            _repositorio.Eliminar(sessao);
            _repositorioTrabalhos.AtualizarTotalHorasParaTrabalho(sessao.TrabalhoId);
            _notification.Success("Sessão eliminada!");
            return RedirectToAction("Index");
        }

    }
}

InkWorks/Controllers/SobreController.cs
using Microsoft.AspNetCore.Mvc;

namespace InkWorks.Controllers
{
    public class SobreController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

InkWorks/Views/Shared/_AreaRestrita.cshtml
@{
    var user = Sessao.BuscarSessaoUtilizador();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ÁREA RESTRITA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InkWorks.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <!--fullcalendar scripts-->
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.9/index.global.min.js"></script>
    <script>

        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendario');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'timeGridWeek',
                events: '/SessoesApi/ObterEventosSessao',
                headerToolbar: {
                    left: 'prev,next today',
                    center: '',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
                },
                navLinks: true, 
                selectable: false,
                
            });
            calendar.getEvents(function (events) {
                console.log('Eventos recebidos da API:', events);
            });
            calendar.render();
        });

    </script>
    
</head>
<body class="container-fluid d-flex flex-column vh-100 justify-content-between">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ÁREA RESTRITA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Trabalhos" asp-action="Index">Trabalhos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Sessoes" asp-action="Index">Marcações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Imagens" asp-action="Index">Imagens</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Mensagens" asp-action="Index">Mensagens</a>
                        </li>
                       
                        
                        @if (user.Perfil == InkWorks.Enums.PerfilEnum.Admin)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white btn btn-outline-danger" asp-area="" asp-controller="Utilizadores" asp-action="Index">Utilizadores</a>
                            </li>
                        }

                        
                        <li class="nav-item">
                            <a class=" btn btn-outline-danger" asp-area="" asp-controller="Login" asp-action="Logout">Log out</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white mx-lg-4" asp-area="" asp-controller="Sobre" asp-action="Index">Sobre este projeto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top text-muted ">
        <div class="container">
            &copy; 2023 - InkWorks - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>






    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

InkWorks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Creative - Start Bootstrap Theme</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
    <link href="css/stylesNotLogged.css" rel="stylesheet" />
</head>
<body>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
    <script src="js/scriptNotLogged.js"></script>
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body> 

InkWorks/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ÁREA RESTRITA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InkWorks.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body class="container-fluid d-flex flex-column vh-100 justify-content-between">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand mr-auto" asp-area="" asp-controller="Home" asp-action="Index">ÁREA RESTRITA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top text-muted ">
        <div class="container">
            &copy; 2023 - InkWorks - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>