InkWorks/Controllers/ImagensController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using InkWorks.Filters;
using InkWorks.Models;
using InkWorks.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace InkWorks.Controllers
{
    [UtilizadorLogado]
    public class ImagensController : Controller
    {
        private readonly IImagemRepositorio _repositorio;
        private readonly ITrabalhoRepositorio _trabalhos;
        private readonly INotyfService _notification;
        public ImagensController(IImagemRepositorio repositorio, INotyfService notification, ITrabalhoRepositorio trabalhos)
        {
            _repositorio = repositorio;
            _notification = notification;
            _trabalhos = trabalhos;
        }
        public IActionResult Index()
        {
            var imagens = _repositorio.ListarTodos();
            var trabalhos = _trabalhos.ListarTodos();

            var viewModel = new ImagemTrabalhoViewModel
            {
                Imagens = imagens,
                Trabalhos = trabalhos
            };

            return View(viewModel);
        }

        public IActionResult Editar(int id)
        {
            Imagem img = _repositorio.ListarPorId(id);
            var trabalhos = _trabalhos.ListarTodos();

            if (img == null)
            {
                _notification.Error("Imagem não encontrada!");
                return RedirectToAction("Index");
            }

            var viewModel = new ImagemTrabalhoViewModel
            {
                Imagens = new List<Imagem> { img },
                Trabalhos = trabalhos
            };

            return View(viewModel);
        }
        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            Imagem img = _repositorio.ListarPorId(id);
            if (img == null)
            {
                _notification.Error("Imagem não encontrada!");
                return RedirectToAction("Index");
            }
            return View(img);
        }




        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile imagem, string titulo, string descricao, bool galeria, int TrabalhoId)
        {
            if (imagem != null && imagem.Length > 0)
            {
                try
                {

                    var uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads");


                    if (!Directory.Exists(uploadsFolder))
                    {
                        Directory.CreateDirectory(uploadsFolder);
                    }


                    var nomeArquivo = Guid.NewGuid().ToString() + Path.GetExtension(imagem.FileName);

                    var caminhoCompleto = Path.Combine(uploadsFolder, nomeArquivo);

                    using (var stream = new FileStream(caminhoCompleto, FileMode.Create))
                    {
                        await imagem.CopyToAsync(stream);
                    }


                    Imagem imagemModel;


                    imagemModel = new Imagem
                    {
                        Url = "/uploads/" + nomeArquivo,
                        Titulo = titulo,
                        Descricao = descricao,
                        Portfolio = galeria,
                        TrabalhoId = TrabalhoId != 0 ? TrabalhoId : (int?)null
                    };


                    _repositorio.Adicionar(imagemModel);

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    _notification.Error("Não Conseguimos carregar a sua imagem :(");
                }
            }

            _notification.Error("Oops!! Algo deu errado! tente novamente!");
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Editar(ImagemTrabalhoViewModel viewModel)
        {

            Imagem imagemExistente = _repositorio.ListarPorId(viewModel.Imagens[0].ImagemId);
            if (imagemExistente != null)
            {
                imagemExistente.Titulo = viewModel.Imagens[0].Titulo;
                imagemExistente.Descricao = viewModel.Imagens[0].Descricao;
                imagemExistente.Portfolio = viewModel.Imagens[0].Portfolio;
                imagemExistente.TrabalhoId = viewModel.TrabalhoId != 0 ? viewModel.TrabalhoId : (int?)null;

                _repositorio.Editar(imagemExistente);
                _notification.Success("Dados da Imagem atualizados!");
                return RedirectToAction("Index");
            }
            else
            {

                _notification.Error("Imagem não encontrada.");
                return View(viewModel);
            }

        }


        public IActionResult ConfirmaEliminar(int id)
        {
            Imagem imagem = _repositorio.ListarPorId(id);

            if (imagem == null)
            {
                _notification.Error("Imagem não encontrada!");
                return RedirectToAction("Index");
            }

            
            _repositorio.Eliminar(imagem);

           
            if (!string.IsNullOrEmpty(imagem.Url))
            {
                var imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", imagem.Url.TrimStart('/'));
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
            }

            _notification.Success("Imagem eliminada");
            return RedirectToAction("Index");
        }


    }
}

InkWorks/Controllers/SessoesController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using InkWorks.Filters;
using InkWorks.Migrations;
using InkWorks.Models;
using InkWorks.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace InkWorks.Controllers
{
    [UtilizadorLogado]
    public class SessoesController : Controller
    {
        private readonly ISessaoRepositorio _repositorio;
        private readonly ITrabalhoRepositorio _repositorioTrabalhos;
        private readonly IClienteRepositorio _repositorioClientes;
        private readonly INotyfService _notification;
        public SessoesController(ISessaoRepositorio repositorio, ITrabalhoRepositorio repositorioTrabalhos, INotyfService notification, IClienteRepositorio repositorioClientes)
        {
            _repositorio = repositorio;
            _repositorioTrabalhos = repositorioTrabalhos;
            _repositorioClientes = repositorioClientes;
            _notification = notification;
        }

        public IActionResult Index()
        {
            //Pedir dados
            List<Sessao> sessoes = _repositorio.ListarTodos();
            if(sessoes == null)
            {
                _notification.Error("Erro ao carregar sessões!");
                return RedirectToAction("Index");
            }
            return View("Index", sessoes);
        }
        public IActionResult Adicionar(int TrabalhoId)
        {
            var trabalho = _repositorioTrabalhos.ListarPorId(TrabalhoId);

            if (trabalho == null)
            {
                _notification.Error("Trabalho não encontrado!");
                return RedirectToAction("Index");
            }

            var sessao = new Sessao
            {
                TrabalhoId = TrabalhoId,
                Trabalho = trabalho
            };
            return View(sessao);
        }
        public IActionResult Detalhes(int id)
        {
            Sessao sessao = _repositorio.ListarPorId(id);
            if (sessao == null)
            {
                _notification.Error("Erro ao carregar detalhes!");
                return RedirectToAction("Index");
            }
            return View(sessao);

        }


        public IActionResult Editar(int id)
        {

            Sessao sessao = _repositorio.ListarPorId(id);
           

            if (sessao == null)
            {
                _notification.Error("Não foi possível editar esta sessão!");
                return RedirectToAction("Index");
            }

            return View(sessao);
        }
        public IActionResult Eliminar(int id)
        {

            Sessao sessao = _repositorio.ListarPorId(id);

            if (sessao == null)
            {
                _notification.Error("Não foi possível apagar esta sessão!");
                return RedirectToAction("Index");
            }


            return View(sessao);
        }

        [HttpPost]
        public IActionResult Adicionar(Sessao sessao)
        {
            if (sessao == null)
            {
                _notification.Error("Erro ao carregar sessão!");
                return RedirectToAction("Index");
            }

            sessao.Duracao = (int)(sessao.DataFinal - sessao.DataInicio).TotalHours;

            _repositorio.Adicionar(sessao);
            _repositorioTrabalhos.AtualizarTotalHorasParaTrabalho(sessao.TrabalhoId);
            _notification.Success("Sessão marcada!");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Editar(Sessao sessao)
        {
            if (sessao == null)
            {
                _notification.Error("Erro ao carregar sessão!");
                return RedirectToAction("Index");
            }
            sessao.Duracao = (int)(sessao.DataFinal - sessao.DataInicio).TotalHours;

            _repositorio.Editar(sessao);
            _repositorioTrabalhos.AtualizarTotalHorasParaTrabalho(sessao.TrabalhoId);
            _notification.Success("Sessão modificada!");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Eliminar(Sessao sessao)
        {
            if (sessao == null)
            {
                _notification.Error("Erro ao carregar sessão!");
                return RedirectToAction("Index");
            }
            _repositorio.Eliminar(sessao);
            _repositorioTrabalhos.AtualizarTotalHorasParaTrabalho(sessao.TrabalhoId);
            _notification.Success("Sessão eliminada!");
            return RedirectToAction("Index");
        }

    }
}

InkWorks/Controllers/TrabalhosController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using InkWorks.Filters;
using InkWorks.Migrations;
using InkWorks.Models;
using InkWorks.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace InkWorks.Controllers
{
    [UtilizadorLogado]
    public class TrabalhosController : Controller
    {
        private readonly ITrabalhoRepositorio _repositorio;
        private readonly IClienteRepositorio _repositorioCliente;
        private readonly INotyfService _notification;
        public TrabalhosController(ITrabalhoRepositorio repositorio, IClienteRepositorio repositorioClientes, INotyfService notification)
        {
            _repositorio = repositorio;
            _repositorioCliente = repositorioClientes;
            _notification = notification;
        }

        public IActionResult Index()
        {
            List<Trabalho> trabalhos = _repositorio.ListarTodos();
            if (trabalhos == null)
            {
                _notification.Error("Erro ao carregar trabalhos!");
                return RedirectToAction("Index");
            }
            return View("Index", trabalhos);
        }
        public IActionResult Adicionar(int ClienteId)
        {
            var cliente = _repositorioCliente.ListarPorId(ClienteId);

            if (cliente == null)
            {
                _notification.Error("Erro ao carregar trabalhos!");
                return RedirectToAction("Index");
            }

            var trabalho = new Trabalho
            {
                ClienteId = ClienteId,
                Cliente = cliente 
            };
            return View(trabalho);
        }
        public IActionResult Detalhes(int id)
        {
            Trabalho trabalho = _repositorio.ListarPorId(id);
            if (trabalho == null)
            {
                _notification.Error("Erro ao carregar trabalho!");
                return RedirectToAction("Index");
            }
            return View(trabalho);

        }


        public IActionResult Editar(int id)
        {

            Trabalho trabalho = _repositorio.ListarPorId(id);

            if (trabalho == null)
            {
                _notification.Error("Erro ao carregar trabalho!");
                return RedirectToAction("Index");
            }

            return View(trabalho);
        }
        public IActionResult Eliminar(int id)
        {

            Trabalho trabalho = _repositorio.ListarPorId(id);

            if (trabalho == null)
            {
                _notification.Error("Erro ao carregar trabalho!");
                return RedirectToAction("Index");
            }


            return View(trabalho);
        }

        [HttpPost]
        public IActionResult Adicionar(Trabalho trabalho)
        {
            if (trabalho == null)
            {
                _notification.Error("Erro ao carregar trabalho!");
                return RedirectToAction("Index");
            }

            _repositorio.Adicionar(trabalho);
            _notification.Success("Trabalho adicionado!");
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Editar(Trabalho trabalho)
        {
            if (trabalho == null)
            {
                _notification.Error("Erro ao carregar trabalho!");
                return RedirectToAction("Index");
            }
            _repositorio.Editar(trabalho);
            _notification.Success("Trabalho editado!");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Eliminar(Trabalho trabalho)
        {
            if (trabalho == null)
            {
                _notification.Error("Erro ao carregar trabalho!");
                return RedirectToAction("Index");
            }
            _repositorio.Eliminar(trabalho);
            _notification.Success("Trabalho eliminado!");


            return RedirectToAction("Index");

        }
    }
}

InkWorks/Views/Trabalhos/Adicionar.cshtml
@model Trabalho

@{
    ViewData["title"] = "Novo trabalho";
}


<div class="container d-flex justify-content-center align-items-center py-4">
    <div class="bg-dark text-white p-4 rounded">
        <h1 class="display-5 mb-4">Adicionar novo Trabalho</h1>

        <form method="post" asp-controller="Trabalhos" asp-action="Adicionar" class="mt-2">
            <div class="mb-3">
                <label for="Titulo" class="form-label">Título:</label>
                <input type="text" class="form-control" asp-for="Titulo" id="Titulo" required>
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>

            
            <input type="hidden" asp-for="ClienteId" id="ClienteId" value="@Model.ClienteId" />

            <div class="mb-3">
                <label for="TotalHoras" class="form-label">Total de Horas:</label>
                <input type="text" class="form-control" asp-for="TotalHoras" id="TotalHoras" required>
                <span asp-validation-for="TotalHoras" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Valor" class="form-label">Valor:</label>
                <input type="text" class="form-control" asp-for="Valor" id="Valor" required>
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Estilo" class="form-label">Estilo:</label>
                <input type="text" class="form-control" asp-for="Estilo" id="Estilo" required>
                <span asp-validation-for="Estilo" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="ObservacoesTrabalho" class="form-label">Observações:</label>
                <input type="text" class="form-control" asp-for="ObservacoesTrabalho" id="Observacoes" required>
                <span asp-validation-for="ObservacoesTrabalho" class="text-danger"></span>
            </div>
            
            <div class="mb-3">
                <label for="Concluido" class="form-label">Concluído:</label>
                <select class="form-control" asp-for="Concluido">
                    <option value="true">Sim</option>
                    <option value="false">Não</option>
                </select>
            </div>
            




            <button type="submit" class="btn btn-outline-success">Guardar</button>
            <a class="btn btn-outline-light" asp-action="Index">Voltar</a>
        </form>

    </div>
</div>

InkWorks/Views/Trabalhos/Detalhes.cshtml
@model Trabalho

<div class="container">
    <h1>Dados do Trabalho</h1>

    <table class="table table-dark">
        <tr>
            <th>Nome:</th>
            <td>@Model.Titulo</td>
        </tr>
        <tr>
            <th>Morada:</th>
            <td>@Model.Estilo</td>
        </tr>
        <tr>
            <th>Cliente:</th>
            <td><a class="btn btn-outline-light" asp-controller="Clientes" asp-action="Detalhes" asp-route-id="@Model.ClienteId">Ver</a></td>
        </tr>
        <tr>
            <th>Concluído:</th>
            <td>@(Model.Concluido ? "Sim" : "Não")</td>
        </tr>
        <tr>
            <td>Nº Sessões:</td>
            <td>@Model.Sessoes?.Count()</td>
        </tr>
        <tr>
            <th>Valor:</th>
            <td>€@string.Format("{0:F2}", Model.Valor)</td>
        </tr>
        <tr>
            <th>Observações:</th>
            <td>@Model.ObservacoesTrabalho</td>

        </tr>
    </table>


    <div class="mb-3">


        <a class="btn btn-outline-success" title="Adicionar Imagens" asp-controller="Imagens" asp-action="Index"><i class="bi bi-file-earmark-plus"></i> Imagens</a>
        <a class="btn btn-outline-success" title="Adicionar sessão" asp-controller="Sessoes" asp-action="Adicionar" asp-route-TrabalhoId="@Model.TrabalhoId"><i class="bi bi-file-earmark-plus"></i> Sessão</a>
        <a class="btn btn-outline-warning" title="Editar dados deste trabalho" asp-controller="Trabalhos" asp-action="Editar" asp-route-id="@Model.TrabalhoId"><i class="bi bi-pencil"></i></a>
        <a class="btn btn-outline-danger" title="Remover Trabalho" asp-controller="Trabalhos" asp-action="Eliminar" asp-route-id="@Model.TrabalhoId"> <i class="bi bi-trash3"></i></a>
        <a class="btn btn-outline-light" asp-controller="Trabalhos" asp-action="Index">Voltar</a>
    </div>

    @if (Model.Imagens != null)
    {
        <h3>Imagens</h3>
        <table id="galeria" class="table table-dark">
            <thead>
                <tr>
                    <th class="text-center">Imagem</th>
                    <th class="text-center">Título</th>
                    <th class="text-center">Descrição</th>
                    <th class="text-center">Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var imagem in Model.Imagens)
                {
                    if (!imagem.Portfolio)
                    {
                        <tr>
                            <td class="text-center align-middle"><img src="@imagem.Url" alt="@imagem.Titulo" width="100"></td>
                            <td class="text-center align-middle">@imagem.Titulo</td>
                            <td class="text-center align-middle">@imagem.Descricao</td>
                            <td class="text-center align-middle">

                                <a class="btn btn-outline-warning" asp-controller="Imagens" asp-action="Editar" asp-route-id="@imagem.ImagemId">Editar</a>
                                <a class="btn btn-outline-danger" asp-controller="Imagens" asp-action="Eliminar" asp-route-Id="@imagem.ImagemId">Remover</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>

    }



</div>

InkWorks/Views/Trabalhos/Editar.cshtml
@model Trabalho

@{
    ViewData["title"] = "Editar Trabalho";
}


<div class="container d-flex justify-content-center align-items-center py-4">
    <div class="bg-dark text-white p-4 rounded">
        <h1 class="display-5 mb-4">Editar Trabalho</h1>

        <form method="post" asp-controller="Trabalhos" asp-action="Editar" class="mt-2">
            
            <input type="text" class="form-control" asp-for="ClienteId" value="@Model.ClienteId" id="Nome" hidden>
                
            
            <div class="mb-3">
                <label for="Titulo" class="form-label">Título:</label>
                <input type="text" class="form-control" asp-for="Titulo" id="Titulo" required>
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>


            <input type="hidden" asp-for="TrabalhoId" id="ClienteId" value="@Model.TrabalhoId" />

            <div class="mb-3">
                <label for="TotalHoras" class="form-label">Total de Horas:</label>
                <input type="text" class="form-control" asp-for="TotalHoras" id="TotalHoras" required>
                <span asp-validation-for="TotalHoras" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Valor" class="form-label">Valor:</label>
                <input type="text" class="form-control" asp-for="Valor" id="Valor" required>
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Estilo" class="form-label">Estilo:</label>
                <input type="text" class="form-control" asp-for="Estilo" id="Estilo" required>
                <span asp-validation-for="Estilo" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="ObservacoesTrabalho" class="form-label">Observações:</label>
                <input type="text" class="form-control" asp-for="ObservacoesTrabalho" id="Observacoes" required>
                <span asp-validation-for="ObservacoesTrabalho" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label for="Concluido" class="form-label">Concluído:</label>
                <select class="form-control" asp-for="Concluido">
                    <option value="true">Sim</option>
                    <option value="false">Não</option>
                </select>
            </div>
            <button type="submit" class="btn btn-outline-success">Guardar</button>
            <a class="btn btn-outline-light" asp-action="Index">Voltar</a>
        </form>

    </div>
</div>

InkWorks/Views/Trabalhos/Eliminar.cshtml
@model Trabalho

@{
    ViewData["title"] = "Apagar Trabalho";
}


<div class="container d-flex justify-content-center align-items-center py-4">
    <div class="bg-dark text-white p-4 rounded">
        <h1 class="display-5 mb-4">Apagar dados de Trabalho</h1>

       <h3 class="text-danger">Tem a certeza que quer apagar os dados deste trabalho</h3>
        <h3 class="text-danger">@Model.Titulo ?</h3>

       <p>Todos os dados serão eliminados permanentemente</p>

        <form method="post" asp-controller="Trabalhos" asp-action="Eliminar">
            
            <input asp-for="TrabalhoId" hidden />
            <button type="submit" class="btn btn-danger">Remover</button>
            <a class="btn btn-outline-light" asp-action="Index">Voltar</a>
        </form>
       

    </div>
</div>

InkWorks/Views/Trabalhos/Index.cshtml
@model IEnumerable<Trabalho>


<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1>Trabalhos</h1>
        <div class="d-flex w-50">
            <div class="input-group ">
            </div>
            
        </div>
    </div>

    <table id="Trabalhos" class="table table-dark table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Título</th>
                <th scope="col">Cliente</th>
                <th scope="col">Total de Horas</th>
                <th scope="col">Nº de Sessões</th>
                <th scope="col">Valor</th>
                <th scope="col">Concluido</th>
                <th scope="col">Opções</th>
            </tr>
        </thead>
        <tbody>

            @if (Model != null)
            {
                foreach (var trabalho in Model)
                {
                    <tr>
                        <th scope="row">@trabalho.TrabalhoId</th>
                        <td>@trabalho.Titulo</td>
                        <td>@trabalho.Cliente?.Nome</td>
                        <td>@trabalho.TotalHoras</td>
                        <td>@trabalho.Sessoes?.Count()</td>
                        <td>€@string.Format("{0:F2}", trabalho.Valor)</td>
                        <td>@(trabalho.Concluido ? "Sim" : "Não")</td>
                        <td class="d-flex justify-content-end gap-2">
                            <a class="btn btn-outline-light" title="Detalhes" asp-controller="Trabalhos" asp-action="Detalhes" asp-route-id="@trabalho.TrabalhoId"><i class="bi bi-three-dots"></i></a>
                            <a class="btn btn-outline-success" title="Adicionar sessão a este trabalho" asp-controller="Sessoes" asp-action="Adicionar" asp-route-TrabalhoId="@trabalho.TrabalhoId"><i class="bi bi-file-earmark-plus"></i> Sessão</a>
                            <a class="btn btn-outline-warning" title="Editar dados de trabalho" asp-controller="Trabalhos" asp-action="Editar" asp-route-id="@trabalho.TrabalhoId"><i class="bi bi-pencil"></i></a>
                            <a class="btn btn-outline-danger" title="Remover trabalho" asp-controller="Trabalhos" asp-action="Eliminar" asp-route-id="@trabalho.TrabalhoId"><i class="bi bi-trash3"></i></a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <div class="m-lg-5"></div>
</div>