InkWorks/Controllers/UtilizadoresController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using InkWorks.Filters;
using InkWorks.Models;
using InkWorks.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace InkWorks.Controllers
{
    [UtilizadorAdmin]
    public class UtilizadoresController : Controller
    {
        private readonly IUtilizadorRepositorio _repositorio;
        private readonly INotyfService _notification;
        public UtilizadoresController(IUtilizadorRepositorio repositorio, INotyfService notification)
        {
            _repositorio = repositorio;
            _notification = notification;
        }
        public IActionResult Index()
        {
            List<Utilizador> utilizadores = _repositorio.ListarTodos();
            if (utilizadores == null)
            {
                _notification.Error("Erro ao carregar utilizadores!");
                return RedirectToAction("Index");
            }
            return View("Index", utilizadores);
        }
        public IActionResult Adicionar()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {

            Utilizador utilizador = _repositorio.ListarPorId(id);
            if (utilizador == null)
            {
                _notification.Error("Erro ao carregar utilizador!");
                return RedirectToAction("Index");
            }


            return View(utilizador);
        }
        public IActionResult Eliminar(int id)
        {

            Utilizador utilizador = _repositorio.ListarPorId(id);

            if (utilizador == null)
            {
                _notification.Error("Erro ao carregar utilizador!");
                return RedirectToAction("Index");
            }

            return View(utilizador);
        }

        [HttpPost]
        public IActionResult Adicionar(Utilizador utilizador)
        {
            if (utilizador == null)
            {
                _notification.Error("Erro ao carregar utilizador!");
                return RedirectToAction("Index");
            }
            _repositorio.Adicionar(utilizador);
            _notification.Success("Utilizador adicionado");
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Editar(Utilizador utilizador)
        {
            if (utilizador == null)
            {
                _notification.Error("Erro ao carregar utilizador!");
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid)
            {
                _repositorio.Editar(utilizador);
                _notification.Success("Utilizador Editado!");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Eliminar(Utilizador utilizador)
        {
            if (utilizador == null)
            {
                _notification.Error("Erro ao carregar utilizador!");
                return RedirectToAction("Index");
            }
            _repositorio.Eliminar(utilizador);
            _notification.Success("Cliente eliminado");


            return RedirectToAction("Index");

        }
    }
}

InkWorks/Views/Utilizadores/Adicionar.cshtml
@model Utilizador
@using InkWorks.Enums;
@{
    ViewData["title"] = "Novo Utilizador";
}

<div class="container d-flex justify-content-center align-items-center py-4">
    <div class="bg-dark text-white p-4 rounded">
        <h1 class="display-5 mb-4">Adicionar novo Utilizador</h1>

        <form method="post" asp-controller="Utilizadores" asp-action="Adicionar" class="mt-2">
            <div class="mb-3">
                <label for="Nome" class="form-label">Nome:</label>
                <input type="text" class="form-control" asp-for="Nome" id="Nome" required>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Email" class "form-label">Email:</label>
                <input type="text" class="form-control" asp-for="Email" id="Email" required>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Perfil" class="form-label">Perfil:</label>
                <select asp-for="Perfil" class="form-control">
                    @foreach (var perfil in Enum.GetValues(typeof(PerfilEnum)))
                    {
                        <option value="@perfil">@perfil</option>
                    }
                </select>
                <span asp-validation-for="Perfil" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Password" class="form-label">Password:</label>
                <input type="password" class="form-control" asp-for="Password" id="Password" required>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <input asp-for="DataCriacao" type="hidden" value="@DateTime.Now" />
            <input asp-for="DataAlteracao" type="hidden" value="@DateTime.Now" />

            <button type="submit" class="btn btn-outline-success">Guardar</button>
            <a class="btn btn-outline-light" asp-action="Index">Voltar</a>
        </form>
    </div>
</div>

InkWorks/Views/Utilizadores/Editar.cshtml
@model Utilizador
@using InkWorks.Enums;

@{
    ViewData["title"] = "Editar Utilizador";
}


<div class="container d-flex justify-content-center align-items-center py-4">
    <div class="bg-dark text-white p-4 rounded">
        <h1 class="display-5 mb-4">Editar Utilizador</h1>

        <form method="post" asp-controller="Utilizadores" asp-action="Editar" class="mt-2">
            
            <input type="text" class="form-control" asp-for="Id" value="@Model.Id" id="Nome" hidden>
                
            <div class="mb-3">
                <label for="Nome" class="form-label">Nome:</label>
                <input type="text" class="form-control" asp-for="Nome" id="Nome" required>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Email" class "form-label">Email:</label>
                <input type="text" class="form-control" asp-for="Email" id="Email" required>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Perfil" class="form-label">Perfil:</label>
                <select asp-for="Perfil" class="form-control">
                    @foreach (var perfil in Enum.GetValues(typeof(PerfilEnum)))
                    {
                        <option value="@perfil">@perfil</option>
                    }
                </select>
                <span asp-validation-for="Perfil" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Password" class="form-label">Password:</label>
                <input type="password" class="form-control" asp-for="Password" id="Password" required>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <input asp-for="DataCriacao" type="hidden" value="@DateTime.Now" />
            <input asp-for="DataAlteracao" type="hidden" value="@DateTime.Now" />

            <button type="submit" class="btn btn-outline-success">Guardar</button>
            <a class="btn btn-outline-light" asp-action="Index">Voltar</a>
        </form>

    </div>
</div>

InkWorks/Views/Utilizadores/Eliminar.cshtml
@model Utilizador

@{
    ViewData["title"] = "Apagar Utilizador";
}


<div class="container d-flex justify-content-center align-items-center py-4">
    <div class="bg-dark text-white p-4 rounded">
        <h1 class="display-5 mb-4">Remover Utilizador</h1>

       <h3 class="text-danger">Tem a certeza que quer Remover o utilizador</h3>
        <h3 class="text-danger">@Model.Nome?</h3>

       <p>Este utilizador deixará de ter acesso à área restrita.</p>

        <form method="post" asp-controller="Utilizadores" asp-action="Eliminar">
            
            <input asp-for="Id" hidden />
            <button type="submit" class="btn btn-danger">Remover</button>
            <a class="btn btn-outline-light" asp-controller="Utilizadores" asp-action="Index">Voltar</a>
        </form>
       

    </div>
</div>

InkWorks/Views/Utilizadores/Index.cshtml
@model IEnumerable<Utilizador>


<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1>Utilizadores</h1>
        <div class="d-flex w-50">
            <div class="input-group ">
            </div>
            <a class="btn btn-outline-success w-75" asp-action="Adicionar"><i class="bi bi-file-earmark-plus"></i> Novo Utilizador</a>
        </div>
    </div>

    <table id="Utilizadores" class="table table-dark table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Perfil</th>
                <th scope="col">Data de Criação</th>
                <th scope="col">Última Alteração</th>
                <th scope="col">opções</th>
            </tr>
        </thead>
        <tbody>

            @if (Model != null)
            {
                foreach (var user in Model)
                {
                    <tr>
                        <th scope="row">@user.Id</th>
                        <td>@user.Nome</td>
                        <td>@user.Email</td>
                        <td>@user.Perfil</td>
                        <td>@user.DataCriacao</td>
                        <td>@user.DataAlteracao</td>
                        <td class="d-flex justify-content-end gap-2">
                            <a class="btn btn-outline-secondary" title="Detalhes" asp-controller="Utilizadores" asp-action="Detalhes" asp-route-id="@user.Id"><i class="bi bi-three-dots"></i></a>
                            <a class="btn btn-outline-warning" title="Editar Utilizador" asp-controller="Utilizadores" asp-action="Editar" asp-route-id="@user.Id"><i class="bi bi-pencil"></i></a>
                            <a class="btn btn-outline-danger" title="Remover Utilizador" asp-controller="Utilizadores" asp-action="Eliminar" asp-route-id="@user.Id"><i class="bi bi-trash3"></i></a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <div class="m-lg-5"></div>
</div>