InkWorks/Controllers/ClientesController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using InkWorks.Filters;
using InkWorks.Models;
using InkWorks.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace InkWorks.Controllers
{
    [UtilizadorLogado]
    public class ClientesController : Controller
    {
        private readonly IClienteRepositorio _repositorio;
        private readonly IMensagemRepositorio _mensagem;
        private readonly ITrabalhoRepositorio _trabalho;
        private readonly INotyfService _notification;
        public ClientesController(IClienteRepositorio repositorio, INotyfService notification, IMensagemRepositorio mensagem, ITrabalhoRepositorio trabalho)
        {
            _repositorio = repositorio;
            _notification = notification;
            _mensagem = mensagem;
            _trabalho = trabalho;
        }
        public IActionResult Index()
        {
            //Pedir dados
            List<Cliente> clientes = _repositorio.ListarTodos();
            // Passa os dados para a view
            return View("Index", clientes);
        }
        public IActionResult Adicionar()
        {
            return View();
        }
        public IActionResult AdicionarPorMsg(int id)
        {
            Mensagem mensagem = _mensagem.ListarPorId(id);

            if (mensagem == null)
            {
                _notification.Error("Não encontrado!");
                return RedirectToAction("Index");
            }

            Cliente novoCliente = new Cliente
            {
                Nome = mensagem.Nome,
                Email = mensagem.Email,
                Morada = mensagem.Morada,
                AnoNascimento = mensagem.AnoNascimento,
                Telefone = mensagem.Telefone,
                MsgId = mensagem.MensagemId
            };


            return View("AdicionarPorMsg", novoCliente);
        }
        public IActionResult Detalhes(int id)
        {

            var cliente = _repositorio.ListarDetalhesPorId(id);
            if (cliente == null)
            {
                _notification.Error("Cliente não encontrado!");
                return RedirectToAction("Index");
            }
            return View(cliente);
        }

        public IActionResult Editar(int id)
        {

            Cliente cliente = _repositorio.ListarPorId(id);

            if (cliente == null)
            {
                _notification.Error("Cliente não encontrado!");
                return RedirectToAction("Index");
            }

            return View(cliente);
        }
        public IActionResult Eliminar(int id)
        {

            Cliente cliente = _repositorio.ListarPorId(id);

            if (cliente == null)
            {
                _notification.Error("Cliente não encontrado!");
                return RedirectToAction("Index");
            }

            return View(cliente);
        }

        [HttpPost]
        public IActionResult Adicionar(Cliente cliente)
        {

            _repositorio.Adicionar(cliente);
            _notification.Success("Cliente adicionado");
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Editar(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _repositorio.Editar(cliente);
                _notification.Success("Cliente Editado!");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Eliminar(Cliente cliente)
        {
            if (cliente == null)
            {
                _notification.Error("Cliente não encontrado!");
                return RedirectToAction("Index");
            }
            _repositorio.Eliminar(cliente);
            _notification.Success("Cliente eliminado");


            return RedirectToAction("Index");

        }
        [HttpPost]
        public IActionResult AdicionarPorMsg(Cliente cliente)
        {
            int? msgIdNullable = cliente.MsgId;
            int msgId = msgIdNullable.HasValue ? msgIdNullable.Value : 0;


            var mensagem = _mensagem.ListarPorId(msgId);

            if (mensagem != null)
            {

                mensagem.Cliente = cliente;
                mensagem.ClienteId = cliente.ClienteId;

                mensagem.Nome = cliente.Nome;
                mensagem.Email = cliente.Email;
                mensagem.Morada = cliente.Morada;
                mensagem.AnoNascimento = cliente.AnoNascimento;
                mensagem.Telefone = cliente.Telefone;

                _repositorio.Adicionar(cliente);

                _notification.Success("Cliente adicionado com a mensagem associada");
                return RedirectToAction("Index");
            }

            //  situação em que não foi encontrada uma mensagem válida
            _notification.Error("A mensagem não pôde ser associada ao cliente.");
            return View("Adicionar", cliente);
        }






    }
}

InkWorks/Controllers/MensagensController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using InkWorks.Filters;
using InkWorks.Models;
using InkWorks.Repositorio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InkWorks.Controllers
{
    [UtilizadorLogado]
    public class MensagensController : Controller
    {
        private readonly IMensagemRepositorio _repositorio;
        private readonly IClienteRepositorio _clientes;
        private readonly INotyfService _notification;
        public MensagensController(IMensagemRepositorio repositorio, INotyfService notification, IClienteRepositorio clientes)
        {
            _repositorio = repositorio;
            _notification = notification;
            _clientes = clientes;
        }
        public IActionResult Index()
        {
            
            List<Mensagem> msgs = _repositorio.ListarTodos();
           
            return View("Index", msgs);
        }
        public IActionResult Enviar()
        {
            return View();
        }
        public IActionResult Atribuir(int id)
        {
            Mensagem mensagem = _repositorio.ListarPorId(id);
            if (mensagem == null)
            {
                _notification.Error("Mensagem não encontrada!");
                return RedirectToAction("Index");
            }
            var clientes = _clientes.ListarTodos();
            if (clientes == null)
            {
                _notification.Error("Erro ao carregar clientes!");
                return RedirectToAction("Index");
            }

            ViewBag.Clientes = new SelectList(clientes, "ClienteId", "Nome");

            return View(mensagem);

        }
        public IActionResult Detalhes(int id)
        {
            var msg = _repositorio.ListarPorId(id);
            if (msg == null)
            {
                _notification.Error("Mensagem não encontrada!");
                return RedirectToAction("Index");
            }
            return View(msg);
        }
        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            var mensagem = _repositorio.ListarPorId(id);

            if (mensagem == null)
            {
                _notification.Error("Mensagem não encontrada!");
                return RedirectToAction("Index");
            }

            return View(mensagem);
        }

        [HttpPost]
        public IActionResult Enviar(Mensagem msg)
        {

            _repositorio.Enviar(msg);
            _notification.Success("Mensagem enviada!");
            return RedirectToAction("Index", "Publico");
        }
        [HttpPost]
        public IActionResult Atribuir(Mensagem msg)
        {
            Mensagem mensagem = _repositorio.ListarPorId(msg.MensagemId);
            if (mensagem == null)
            {
                _notification.Error("Mensagem não encontrada!");
                return RedirectToAction("Index");
            }
            mensagem.ClienteId = msg.ClienteId;

            _repositorio.Editar(mensagem);
            _notification.Success("Mensagem Atribuida!");

            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Eliminar(Mensagem mensagem)
        {
            var mensagemParaEliminar = _repositorio.ListarPorId(mensagem.MensagemId);

            if (mensagemParaEliminar == null)
            {
                _notification.Error("Mensagem não encontrada!");
                return RedirectToAction("Index");
            }

            _repositorio.Eliminar(mensagemParaEliminar);
            _notification.Success("Mensagem eliminada com sucesso!");

            return RedirectToAction("Index");
        }


    }
}

InkWorks/Controllers/TrabalhosController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using InkWorks.Filters;
using InkWorks.Migrations;
using InkWorks.Models;
using InkWorks.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace InkWorks.Controllers
{
    [UtilizadorLogado]
    public class TrabalhosController : Controller
    {
        private readonly ITrabalhoRepositorio _repositorio;
        private readonly IClienteRepositorio _repositorioCliente;
        private readonly INotyfService _notification;
        public TrabalhosController(ITrabalhoRepositorio repositorio, IClienteRepositorio repositorioClientes, INotyfService notification)
        {
            _repositorio = repositorio;
            _repositorioCliente = repositorioClientes;
            _notification = notification;
        }

        public IActionResult Index()
        {
            List<Trabalho> trabalhos = _repositorio.ListarTodos();
            if (trabalhos == null)
            {
                _notification.Error("Erro ao carregar trabalhos!");
                return RedirectToAction("Index");
            }
            return View("Index", trabalhos);
        }
        public IActionResult Adicionar(int ClienteId)
        {
            var cliente = _repositorioCliente.ListarPorId(ClienteId);

            if (cliente == null)
            {
                _notification.Error("Erro ao carregar trabalhos!");
                return RedirectToAction("Index");
            }

            var trabalho = new Trabalho
            {
                ClienteId = ClienteId,
                Cliente = cliente 
            };
            return View(trabalho);
        }
        public IActionResult Detalhes(int id)
        {
            Trabalho trabalho = _repositorio.ListarPorId(id);
            if (trabalho == null)
            {
                _notification.Error("Erro ao carregar trabalho!");
                return RedirectToAction("Index");
            }
            return View(trabalho);

        }


        public IActionResult Editar(int id)
        {

            Trabalho trabalho = _repositorio.ListarPorId(id);

            if (trabalho == null)
            {
                _notification.Error("Erro ao carregar trabalho!");
                return RedirectToAction("Index");
            }

            return View(trabalho);
        }
        public IActionResult Eliminar(int id)
        {

            Trabalho trabalho = _repositorio.ListarPorId(id);

            if (trabalho == null)
            {
                _notification.Error("Erro ao carregar trabalho!");
                return RedirectToAction("Index");
            }


            return View(trabalho);
        }

        [HttpPost]
        public IActionResult Adicionar(Trabalho trabalho)
        {
            if (trabalho == null)
            {
                _notification.Error("Erro ao carregar trabalho!");
                return RedirectToAction("Index");
            }

            _repositorio.Adicionar(trabalho);
            _notification.Success("Trabalho adicionado!");
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Editar(Trabalho trabalho)
        {
            if (trabalho == null)
            {
                _notification.Error("Erro ao carregar trabalho!");
                return RedirectToAction("Index");
            }
            _repositorio.Editar(trabalho);
            _notification.Success("Trabalho editado!");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Eliminar(Trabalho trabalho)
        {
            if (trabalho == null)
            {
                _notification.Error("Erro ao carregar trabalho!");
                return RedirectToAction("Index");
            }
            _repositorio.Eliminar(trabalho);
            _notification.Success("Trabalho eliminado!");


            return RedirectToAction("Index");

        }
    }
}

InkWorks/Views/Clientes/Adicionar.cshtml
@model Cliente

@{
    ViewData["title"] = "Novo Cliente";
}


<div class="container d-flex justify-content-center align-items-center py-4">
    <div class="bg-dark text-white p-4 rounded">
        <h1 class="display-5 mb-4">Adicionar novo Cliente</h1>

        <form method="post" asp-controller="Clientes" asp-action="Adicionar" class="mt-2">
            <div class="mb-3">
                <label for="Nome" class="form-label">Nome:</label>
                <input type="text" class="form-control" asp-for="Nome" id="Nome" required>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Morada" class="form-label">Morada:</label>
                <input type="text" class="form-control" asp-for="Morada" id="Morada" required>
                <span asp-validation-for="Morada" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="AnoNascimento" class="form-label">Ano de Nascimento:</label>
                <input type="text" class="form-control" asp-for="AnoNascimento" id="AnoNascimento" required>
                <span asp-validation-for="AnoNascimento" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Telefone" class="form-label">Contacto:</label>
                <input type="text" class="form-control" asp-for="Telefone" id="Telefone" required>
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Email" class="form-label">Email:</label>
                <input type="text" class="form-control" asp-for="Email" id="Email" required>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Observacoes" class="form-label">Observaçõess:</label>
                <input type="text" class="form-control" asp-for="Observacoes" id="Observacoes">
                <span asp-validation-for="Observacoes" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-outline-success">Guardar</button>
            <a class="btn btn-outline-light" asp-action="Index">Voltar</a>
        </form>

    </div>
</div>

InkWorks/Views/Clientes/AdicionarPorMsg.cshtml
@model Cliente

@{
    ViewData["title"] = "Novo Cliente";
}


<div class="container d-flex justify-content-center align-items-center py-4">
    <div class="bg-dark text-white p-4 rounded">
        <h1 class="display-5 mb-4">Adicionar novo Cliente</h1>

        <form method="post" asp-controller="Clientes" asp-action="AdicionarPorMsg" class="mt-2">
            <div class="mb-3">
                <label for="Nome" class="form-label">Nome:</label>
                <input type="text" class="form-control" asp-for="Nome" id="Nome" required>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Morada" class="form-label">Morada:</label>
                <input type="text" class="form-control" asp-for="Morada" id="Morada" required>
                <span asp-validation-for="Morada" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="AnoNascimento" class="form-label">Ano de Nascimento:</label>
                <input type="text" class="form-control" asp-for="AnoNascimento" id="AnoNascimento" required>
                <span asp-validation-for="AnoNascimento" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Telefone" class="form-label">Contacto:</label>
                <input type="text" class="form-control" asp-for="Telefone" id="Telefone" required>
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Email" class="form-label">Email:</label>
                <input type="text" class="form-control" asp-for="Email" id="Email" required>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Observacoes" class="form-label">Observaçõess:</label>
                <input type="text" class="form-control" asp-for="Observacoes" id="Observacoes" required>
                <span asp-validation-for="Observacoes" class="text-danger"></span>
            </div>
            
                
                <input type="text" class="form-control" asp-for="MsgId" id="MsgId" hidden>
            

            <button type="submit" class="btn btn-outline-success">Guardar</button>
            <a class="btn btn-outline-light" asp-controller="Mensagens" asp-action="Index">Voltar</a>
        </form>

    </div>
</div>

InkWorks/Views/Clientes/Detalhes.cshtml
@model Cliente

<div class="container">
    <h1>Ficha de Cliente</h1>

    <table class="table table-dark">
        <tr>
            <th>Nome:</th>
            <td>@Model.Nome</td>
        </tr>
        <tr>
            <th>Morada:</th>
            <td>@Model.Morada</td>
        </tr>
        <tr>
            <th>Telefone:</th>
            <td>@Model.Telefone</td>
        </tr>
        <tr>
            <th>Email:</th>
            <td>@Model.Email</td>
        </tr>
        <tr>
            <th>Ano de Nascimento:</th>
            <td>@Model.AnoNascimento</td>
        </tr>
        <tr>
            <th>Observações:</th>
            <td>@Model.Observacoes</td>
        </tr>
    </table>
    

    <div class="mb-3">
        
        
        <a class="btn btn-outline-success" title="Adicionar Trabalho a este cliente" asp-controller="Trabalhos" asp-action="Adicionar" asp-route-ClienteId="@Model.ClienteId"><i class="bi bi-file-earmark-plus"></i></a>
        <a class="btn btn-outline-warning" title="Editar dados de cliente" asp-controller="Clientes" asp-action="Editar" asp-route-id="@Model.ClienteId"><i class="bi bi-pencil"></i></a>
        <a class="btn btn-outline-danger" title="Remover cliente" asp-controller="Clientes" asp-action="Eliminar" asp-route-id="@Model.ClienteId"> <i class="bi bi-trash3"></i></a>
        <a class="btn btn-outline-light" asp-controller="Mensagens" asp-action="Index">Voltar</a>
    </div>
    <h3>Hisórico de trabalhos</h3>
    <table class="table table-dark">

        <tr>
            <th>Titulo</th>
            <th>Nº Sessões</th>
            <th>Estilo</th>
            <th>Observações</th>
            <th>Valor</th>
            <th>Concluído?</th>
            <th>Opções</th>

        </tr>
        @if (Model.Trabalhos != null)
        {
            foreach (var trabalho in Model.Trabalhos)
            {
                <tr>
                    <td>@trabalho.Titulo</td>
                    <td>@trabalho.Sessoes?.Count()</td>
                    <td>@trabalho.Estilo</td>
                    <td>@trabalho.ObservacoesTrabalho</td>
                    <td>€@string.Format("{0:F2}", trabalho.Valor)</td>
                    <td>@(trabalho.Concluido ? "Sim" : "Não")</td>
                    <td class="gap-2">
                        <a class="btn btn-secondary" title="Detalhes" asp-controller="Trabalhos" asp-action="Detalhes" asp-route-id="@trabalho.TrabalhoId"><i class="bi bi-three-dots"></i></a>
                        <a class="btn btn-warning" title="Editar dados deste trabalho" asp-controller="Trabalhos" asp-action="Editar" asp-route-id="@trabalho.TrabalhoId"><i class="bi bi-pencil"></i></a>
                        <a class="btn btn-danger" title="Remover trabalho" asp-controller="Trabalhos" asp-action="Eliminar" asp-route-id="@trabalho.TrabalhoId"><i class="bi bi-trash3"></i></a>
                    </td>

                </tr>
            }
        }
    </table>
    <h3>Hisórico de Mensagens</h3>
    <table class="table table-dark">

        <tr>
            <th>Recebida</th>
            <th>Mensagem</th>
            
            <th>Opções</th>

        </tr>
        @if (Model.Mensagens != null)
        {
            foreach (var msg in Model.Mensagens)
            {
                <tr>
                    <td>@msg.DataEnvio</td>
                    <td>
                        <a asp-action="Detalhes" asp-route-id="@msg.MensagemId">@Html.Raw(msg.MensagemTexto.Length > 75 ? msg.MensagemTexto.Substring(0, 35) + "..." : msg.MensagemTexto)</a>
                    </td>
                    <td class="gap-2">
                        <a class="btn btn-secondary" title="Detalhes" asp-controller="Mensagens" asp-action="Detalhes" asp-route-id="@msg.MensagemId"><i class="bi bi-three-dots"></i></a>
                        <a class="btn btn-danger" title="Remover trabalho" asp-controller="Mensagens" asp-action="Eliminar" asp-route-id="@msg.MensagemId"><i class="bi bi-trash3"></i></a>
                    </td>

                </tr>
            }
        }
    </table>

</div>

InkWorks/Views/Clientes/Editar.cshtml
@model Cliente

@{
    ViewData["title"] = "Editar Cliente";
}


<div class="container d-flex justify-content-center align-items-center py-4">
    <div class="bg-dark text-white p-4 rounded">
        <h1 class="display-5 mb-4">Editar Ficha de Cliente</h1>

        <form method="post" asp-controller="Clientes" asp-action="Editar" class="mt-2">
            
            <input type="text" class="form-control" asp-for="ClienteId" value="@Model.ClienteId" id="Nome" hidden>
                
            
            <div class="">
                <label for="Nome" class="form-label">Nome:</label>
                <input type="text" class="form-control" asp-for="Nome" id="Nome" required>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Morada" class="form-label">Morada:</label>
                <input type="text" class="form-control" asp-for="Morada" id="Morada" required>
                <span asp-validation-for="Morada" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="AnoNascimento" class="form-label">Ano de Nascimento:</label>
                <input type="text" class="form-control" asp-for="AnoNascimento" id="AnoNascimento" required>
                <span asp-validation-for="AnoNascimento" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Telefone" class="form-label">Contacto:</label>
                <input type="text" class="form-control" asp-for="Telefone" id="Telefone" required>
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Email" class="form-label">Email:</label>
                <input type="text" class="form-control" asp-for="Email" id="Email">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="Observacoes" class="form-label">Observaçõess:</label>
                <input type="text" class="form-control" asp-for="Observacoes" id="Observacoes" required>
                <span asp-validation-for="Observacoes" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-outline-success">Guardar</button>
            <a class="btn btn-outline-light" asp-action="Index">Voltar</a>
        </form>

    </div>
</div>

InkWorks/Views/Clientes/Index.cshtml
@model IEnumerable<Cliente>


<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1>Clientes</h1>
        <div class="d-flex w-50">
            <div class="input-group ">
            </div>
            <a class="btn btn-outline-success w-75" asp-action="Adicionar"><i class="bi bi-file-earmark-plus"></i> Novo Cliente</a>
        </div>
    </div>

    <table id="Clientes" class="table table-dark table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Morada</th>
                <th scope="col">Ano de Nascimento</th>
                <th scope="col">Telefone</th>
                <th scope="col">Email</th>
                <th scope="col">opções</th>
            </tr>
        </thead>
        <tbody>

            @if (Model != null)
            {
                foreach (var cliente in Model)
                {
                    <tr>
                        <th scope="row">@cliente.ClienteId</th>
                        <td>@cliente.Nome</td>
                        <td>@cliente.Morada</td>
                        <td>@cliente.AnoNascimento</td>
                        <td>@cliente.Telefone</td>
                        <td>@cliente.Email</td>
                        <td class="d-flex justify-content-end gap-2">
                            <a class="btn btn-secondary" title="Detalhes" asp-controller="Clientes" asp-action="Detalhes" asp-route-id="@cliente.ClienteId"><i class="bi bi-three-dots"></i></a>
                            <a class="btn btn-outline-success" title="Adicionar Trabalho a este cliente" asp-controller="Trabalhos" asp-action="Adicionar" asp-route-ClienteId="@cliente.ClienteId"><i class="bi bi-file-earmark-plus"></i></a>
                            <a class="btn btn-outline-warning" title="Editar dados de cliente" asp-controller="Clientes" asp-action="Editar" asp-route-id="@cliente.ClienteId"><i class="bi bi-pencil"></i></a>
                            <a class="btn btn-outline-danger" title="Remover cliente" asp-controller="Clientes" asp-action="Eliminar" asp-route-id="@cliente.ClienteId"><i class="bi bi-trash3"></i></a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <div class="m-lg-5"></div>
</div>